# On pourrait ne pas avoir a mettre App\Controller et l'intégré automatiquement dans le router (au niveau du dispatcher)
homepage:
    method:     'GET' 
    path:       '/'
    controller: 'App\Controller\HomeController'
    action:     'homepage'
blog_index:
    method:     ['GET', 'POST']
    path:       '/blog'
    controller: 'App\Controller\BlogController'
    action:     'index'
blog_view:
    method:     'GET' 
    path:       '/blog/{id:\d+}'
    controller: 'App\Controller\BlogController'
    action:  
categorie_index:
    method:     ['GET', 'POST']
    path:       '/category'
    controller: 'App\Controller\CategorieController'
    action:     'index'
categorie_view:
    method:     'GET' 
    path:       '/category/{id:\d+}'
    controller: 'App\Controller\CategorieController'
    action:     'view'